// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtRe4krtTlh9Ak_ONcYR4COiPVvmVW_gg',
    appId: '1:5815954071:web:6880b91152efa5a9b317d2',
    messagingSenderId: '5815954071',
    projectId: 'red-readingenglishdevelopment',
    authDomain: 'red-readingenglishdevelopment.firebaseapp.com',
    storageBucket: 'red-readingenglishdevelopment.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMr81_tbgBBO9Z5Q-eGySf_1iqO3aieas',
    appId: '1:5815954071:android:66db8b1fb15572d1b317d2',
    messagingSenderId: '5815954071',
    projectId: 'red-readingenglishdevelopment',
    storageBucket: 'red-readingenglishdevelopment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2zPTUQp86AlAKtbBcYnGQ9WGhKpFlQaU',
    appId: '1:5815954071:ios:4484a2d2739996c1b317d2',
    messagingSenderId: '5815954071',
    projectId: 'red-readingenglishdevelopment',
    storageBucket: 'red-readingenglishdevelopment.firebasestorage.app',
    iosBundleId: 'com.redreading.red',
  );
}
