import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';

import 'data/repositories/auth_repository.dart';
import 'data/repositories/content_repository.dart';
import 'data/repositories/progress_repository.dart';
import 'data/services/auth_service.dart';
import 'data/services/content_cache.dart';
import 'data/services/content_service.dart';
import 'data/services/firebase_auth_service.dart';
import 'data/services/local_auth_service.dart';
import 'data/services/pdf_service.dart';
import 'data/services/progress_service.dart';
import 'data/services/speech_service.dart';
import 'domain/use_cases/answer_grader.dart';
import 'firebase_options.dart';
import 'routing/app_router.dart';
import 'ui/core/theme/app_theme.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final backend = await _createBackend();
  final content = ContentRepository(
    bundled: const BundledContentSource(),
    cache: ContentCache(),
    cloud: backend.cloudContent,
  );
  await content.load();

  final auth = AuthRepository(service: backend.auth);
  final progress = ProgressRepository(auth: auth, service: backend.progress);

  // Content in Firestore can only be read when signed in, so look for newly
  // published stories whenever someone is signed in.
  void refreshContent() {
    if (auth.isSignedIn) content.refreshFromCloud();
  }

  auth.addListener(refreshContent);

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider.value(value: auth),
        ChangeNotifierProvider.value(value: progress),
        ChangeNotifierProvider.value(value: content),
        Provider(create: (_) => PdfService()),
        Provider<SpeechService>(
          create: (_) => DeviceSpeechService(),
          dispose: (_, speech) => speech.dispose(),
        ),
        Provider(create: (_) => const AnswerGrader()),
      ],
      child: RedApp(auth: auth),
    ),
  );
}

typedef _Backend = ({AuthService auth, ProgressService progress, CloudContentSource? cloudContent});

/// Uses Firebase when `lib/firebase_options.dart` has been generated by
/// `flutterfire configure`; otherwise runs in offline demo mode with the
/// stories bundled in the app.
Future<_Backend> _createBackend() async {
  FirebaseOptions? options;
  try {
    options = DefaultFirebaseOptions.currentPlatform;
  } on UnsupportedError catch (e) {
    debugPrint('RED: ${e.message} Running in offline demo mode.');
  }
  if (options == null) {
    return (auth: LocalAuthService(), progress: LocalProgressService(), cloudContent: null);
  }

  await Firebase.initializeApp(options: options);
  return (
    auth: FirebaseAuthService(),
    progress: FirestoreProgressService(),
    cloudContent: FirestoreContentSource(),
  );
}

class RedApp extends StatefulWidget {
  const RedApp({super.key, required this.auth});

  final AuthRepository auth;

  @override
  State<RedApp> createState() => _RedAppState();
}

class _RedAppState extends State<RedApp> {
  late final GoRouter _router = createRouter(widget.auth);

  @override
  void dispose() {
    _router.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'RED - Reading English Development',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light(),
      routerConfig: _router,
    );
  }
}
